package analyze

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

const executiveTmpl = `# groot analyze

## Archive

{{- if .ArchivePath }}
- **path:** {{.ArchivePath}}
{{- end }}
{{- if .RunID }}
- **run_id:** {{.RunID}}
{{- end }}
{{- if .ArchiveSHA256 }}
- **archive_sha256:** {{.ArchiveSHA256}}
{{- end }}
{{- if .ArchiveLayoutVersion }}
- **archive_layout_version:** {{.ArchiveLayoutVersion}}
{{- end }}

## Disclaimer

Findings below are **hints** and **hypotheses** derived from offline archive evidence.
They are not a definitive root-cause diagnosis. Treat open questions as investigation prompts.

## Summary

{{.Summary}}

## Hints
{{- if .Hints }}
{{- range $i, $h := .Hints }}

### {{add $i 1}}. {{$h.Title}}

- **kind:** {{$h.Kind}}
- **severity:** {{$h.Severity}}
- **summary:** {{$h.Summary}}
{{- if $h.Evidence }}
- **evidence:**
{{- range $h.Evidence }}
  - ` + "`{{.Path}}`" + `
{{- if .Excerpt }}
` + "```" + `
{{.Excerpt}}
` + "```" + `
{{- end }}
{{- end }}
{{- end }}
{{- if $h.OpenQuestions }}
- **open questions:**
{{- range $h.OpenQuestions }}
  - {{.}}
{{- end }}
{{- end }}
{{- end }}
{{- else }}

_No hints emitted._
{{- end }}

## Notes
{{- if .Notes }}
{{- range .Notes }}
- {{if .Code}}` + "`{{.Code}}`" + `: {{end}}{{.Message}}{{if .Path}} ({{.Path}}){{end}}
{{- end }}
{{- else }}

_None._
{{- end }}

---
generated by groot analyze
`

var executiveTemplate = template.Must(
	template.New("executive").
		Option("missingkey=error").
		Funcs(template.FuncMap{
			"add": func(a, b int) int { return a + b },
		}).
		Parse(executiveTmpl),
)

// RenderExecutive renders Report as executive Markdown (ANLZ-05).
func RenderExecutive(r Report) (string, error) {
	var buf bytes.Buffer
	if err := executiveTemplate.Execute(&buf, r); err != nil {
		return "", fmt.Errorf("render executive markdown: %w", err)
	}
	out := buf.String()
	// Normalize trailing whitespace for stable goldens.
	return strings.TrimRight(out, " \t") + "\n", nil
}
