package analyze

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/google/go-cmp/cmp"
	"github.com/hrodrig/groot/internal/archive"
	"github.com/hrodrig/groot/internal/arcread"
)

func TestDefaultLLMBudgetBytes(t *testing.T) {
	if DefaultLLMBudgetBytes != 32768 {
		t.Fatalf("DefaultLLMBudgetBytes = %d, want 32768", DefaultLLMBudgetBytes)
	}
}

func TestRenderLLM_SyntheticPureNoArchive(t *testing.T) {
	longExcerpt := strings.Repeat("x", 400)
	rep := Report{
		RunID:         "run-synth-001",
		ArchiveSHA256: "deadbeef",
		Summary:       "1 hint (CrashLoopBackOff)",
		Hints: []Hint{{
			Kind:     KindCrashLoopBackOff,
			Severity: SeverityError,
			Title:    "CrashLoopBackOff for demo/nginx",
			Summary:  "Pod may be crash-looping based on events",
			Evidence: []Evidence{{
				Path:    "extras/all-cluster-events.log",
				Excerpt: longExcerpt,
			}},
		}},
		Notes: []Note{{
			Code:    "member_missing",
			Message: "optional member not found",
			Path:    "extras/all-pods-wide.txt",
		}},
	}

	md, err := RenderLLM(rep)
	if err != nil {
		t.Fatalf("RenderLLM: %v", err)
	}
	for _, want := range []string{
		"## Instructions for the assistant",
		"hint or hypothesis",
		"run-synth-001",
		"deadbeef",
		"CrashLoopBackOff",
		"extras/all-cluster-events.log",
		"## Secrets warning",
		"unredacted archive text",
		"`.log`",
		"generated by groot analyze --output llm",
	} {
		if !strings.Contains(md, want) {
			t.Fatalf("markdown missing %q:\n%s", want, md)
		}
	}
	if strings.Contains(strings.ToLower(md), "root cause is") {
		t.Fatalf("must not claim definitive root cause:\n%s", md)
	}
	if !strings.Contains(md, "**not** claimed ChatGPT-safe") {
		t.Fatalf("secrets warning must deny ChatGPT-safe claim:\n%s", md)
	}

	// Excerpt clipped at render time to llmExcerptMaxRunes (+ ellipsis).
	excerpt := extractFencedExcerpt(md)
	if n := utf8.RuneCountInString(strings.TrimSuffix(excerpt, "…")); n > llmExcerptMaxRunes {
		t.Fatalf("excerpt runes = %d, want <= %d (%q)", n, llmExcerptMaxRunes, excerpt)
	}
	// Caller Report must be unchanged.
	if utf8.RuneCountInString(rep.Hints[0].Evidence[0].Excerpt) != 400 {
		t.Fatalf("RenderLLM mutated caller Report excerpt")
	}
	if len(md) > DefaultLLMBudgetBytes {
		t.Fatalf("len(md)=%d > DefaultLLMBudgetBytes", len(md))
	}
}

func TestRenderLLM_CrashLoopGolden(t *testing.T) {
	rep := runFixtureReport(t, "crashloop")
	// Temp pack paths are not golden-stable; identity is covered by run_id/sha.
	rep.ArchivePath = ""
	md, err := RenderLLM(rep)
	if err != nil {
		t.Fatalf("RenderLLM: %v", err)
	}
	for _, want := range []string{
		"## Instructions for the assistant",
		"run-crashloop-001",
		"abc123deadbeef0123456789abcdef",
		"CrashLoopBackOff",
		"## Secrets warning",
		"unredacted",
		"generated by groot analyze --output llm",
	} {
		if !strings.Contains(md, want) {
			t.Fatalf("missing %q:\n%s", want, md)
		}
	}
	lower := strings.ToLower(md)
	if strings.Contains(lower, "root cause is") || strings.Contains(lower, "diagnosed as") {
		t.Fatalf("definitive diagnosis language forbidden:\n%s", md)
	}

	goldenPath := filepath.Join("testdata", "llm_crashloop.golden.md")
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(goldenPath, []byte(md), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden (run UPDATE_GOLDEN=1): %v", err)
	}
	if diff := cmp.Diff(string(want), md); diff != "" {
		t.Fatalf("golden mismatch (-want +got):\n%s", diff)
	}
}

func TestRenderLLM_Healthy(t *testing.T) {
	rep := runFixtureReport(t, "healthy")
	md, err := RenderLLM(rep)
	if err != nil {
		t.Fatalf("RenderLLM: %v", err)
	}
	if !strings.Contains(md, "## Instructions for the assistant") {
		t.Fatalf("missing instructions:\n%s", md)
	}
	if !strings.Contains(md, "## Secrets warning") {
		t.Fatalf("missing secrets warning:\n%s", md)
	}
	if strings.Contains(md, "CrashLoopBackOff") {
		t.Fatalf("healthy must not include CrashLoopBackOff:\n%s", md)
	}
	if !strings.Contains(md, "generated by groot analyze --output llm") {
		t.Fatalf("missing llm footer:\n%s", md)
	}
}

func TestRenderLLM_ExecutiveFooterDiffers(t *testing.T) {
	rep := Report{
		RunID:   "run-x",
		Summary: "empty",
	}
	execMD, err := RenderExecutive(rep)
	if err != nil {
		t.Fatalf("RenderExecutive: %v", err)
	}
	llmMD, err := RenderLLM(rep)
	if err != nil {
		t.Fatalf("RenderLLM: %v", err)
	}
	if !strings.Contains(execMD, "generated by groot analyze\n") &&
		!strings.HasSuffix(strings.TrimRight(execMD, "\n"), "generated by groot analyze") {
		t.Fatalf("executive footer missing:\n%s", execMD)
	}
	if strings.Contains(execMD, "--output llm") {
		t.Fatalf("executive must not use llm footer:\n%s", execMD)
	}
	if !strings.Contains(llmMD, "generated by groot analyze --output llm") {
		t.Fatalf("llm footer missing:\n%s", llmMD)
	}
}

func TestRenderLLM_FatReportRespectsCeiling(t *testing.T) {
	rep := fatReport(80, 500)
	md, err := RenderLLM(rep)
	if err != nil {
		t.Fatalf("RenderLLM: %v", err)
	}
	if len(md) > DefaultLLMBudgetBytes {
		t.Fatalf("len=%d exceeds DefaultLLMBudgetBytes=%d", len(md), DefaultLLMBudgetBytes)
	}
	for _, want := range []string{
		"## Instructions for the assistant",
		"## Secrets warning",
		"generated by groot analyze --output llm",
	} {
		if !strings.Contains(md, want) {
			t.Fatalf("framing missing %q after shrink:\n%s", want, md)
		}
	}
}

func TestRenderLLM_TinyBudgetOmitMarker(t *testing.T) {
	// One retained hint with a huge summary forces head/tail after excerpt shrink.
	rep := Report{
		RunID:         "run-omit",
		ArchiveSHA256: "omitsha",
		Summary:       "omit stress",
		Hints: []Hint{{
			Kind:     KindCrashLoopBackOff,
			Severity: SeverityError,
			Title:    "huge hint " + strings.Repeat("T", 200),
			Summary:  strings.Repeat("SUMMARY-LINE\n", 400),
			Evidence: []Evidence{{
				Path:    "extras/all-cluster-events.log",
				Excerpt: strings.Repeat("E", 400),
			}},
			OpenQuestions: []string{strings.Repeat("Q", 300)},
		}},
	}
	budget := 2800
	md, err := renderLLM(rep, budget)
	if err != nil {
		t.Fatalf("renderLLM: %v", err)
	}
	if len(md) > budget {
		t.Fatalf("len=%d > budget=%d", len(md), budget)
	}
	if !strings.Contains(md, "[omitted") || !strings.Contains(md, "bytes]") {
		t.Fatalf("expected visible omit marker, got:\n%s", md)
	}
	if !strings.Contains(md, "… [omitted") {
		t.Fatalf("omit marker must use locked ellipsis form:\n%s", md)
	}
	for _, want := range []string{
		"## Instructions for the assistant",
		"## Secrets warning",
		"unredacted archive text",
		"generated by groot analyze --output llm",
	} {
		if !strings.Contains(md, want) {
			t.Fatalf("must keep framing/warning/footer (%q missing):\n%s", want, md)
		}
	}
}

func TestRenderLLM_FramingOverflowErrors(t *testing.T) {
	rep := Report{Summary: "x", Hints: []Hint{{
		Kind: KindNotReady, Severity: SeverityInfo, Title: "t", Summary: "s",
	}}}
	_, err := renderLLM(rep, 64)
	if err == nil {
		t.Fatal("expected framing overflow error")
	}
	if !strings.Contains(err.Error(), "framing exceeds budget") {
		t.Fatalf("error = %v", err)
	}
}

func TestRenderLLM_NoArcreadImport(t *testing.T) {
	src, err := os.ReadFile("render_llm.go")
	if err != nil {
		t.Fatalf("read render_llm.go: %v", err)
	}
	if strings.Contains(string(src), "arcread") {
		t.Fatal("render_llm.go must not import or reference arcread")
	}
	// Soft check: file should not call Run / open archives.
	if strings.Contains(string(src), "Run(") && strings.Contains(string(src), "arcread.Open") {
		t.Fatal("render_llm.go must remain pure over Report")
	}
}

func TestHeadTailOmit_VisibleMarker(t *testing.T) {
	s := strings.Repeat("abcdefghij", 100) // 1000 bytes
	out := headTailOmit(s, 120)
	if len(out) > 120 {
		t.Fatalf("len=%d > 120", len(out))
	}
	if !strings.Contains(out, "[omitted") || !strings.Contains(out, "bytes]") {
		t.Fatalf("missing omit marker: %q", out)
	}
	if !strings.HasPrefix(out, "abc") {
		t.Fatalf("expected head retained: %q", out)
	}
}

func runFixtureReport(t *testing.T, name string) Report {
	t.Helper()
	src := filepath.Join("testdata", name)
	out := filepath.Join(t.TempDir(), name+".tar.gz")
	if err := archive.DirToTarGz(src, out); err != nil {
		t.Fatalf("DirToTarGz: %v", err)
	}
	arc, err := arcread.Open(out)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer arc.Close()
	rep, err := Run(arc)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	return rep
}

func fatReport(hints, excerptRunes int) Report {
	ex := strings.Repeat("Z", excerptRunes)
	rep := Report{
		RunID:         "run-fat",
		ArchiveSHA256: "fatsha",
		Summary:       "many hints",
	}
	for i := 0; i < hints; i++ {
		rep.Hints = append(rep.Hints, Hint{
			Kind:     KindCrashLoopBackOff,
			Severity: SeverityError,
			Title:    "hint " + strings.Repeat("T", 8) + " " + strings.Repeat("0", i%10),
			Summary:  "summary " + strings.Repeat("S", 40),
			Evidence: []Evidence{{
				Path:    "extras/all-cluster-events.log",
				Excerpt: ex,
			}},
		})
	}
	for i := 0; i < 5; i++ {
		rep.Notes = append(rep.Notes, Note{
			Code:    "note",
			Message: strings.Repeat("note-message-", 20),
			Path:    "extras/x.txt",
		})
	}
	return rep
}

func extractFencedExcerpt(md string) string {
	const fence = "```"
	i := strings.Index(md, fence)
	if i < 0 {
		return ""
	}
	rest := md[i+len(fence):]
	// skip optional language / blank
	if nl := strings.IndexByte(rest, '\n'); nl >= 0 {
		rest = rest[nl+1:]
	}
	j := strings.Index(rest, fence)
	if j < 0 {
		return strings.TrimSpace(rest)
	}
	return strings.TrimRight(rest[:j], "\n")
}
