package analyze_test

import (
	"strings"
	"testing"

	"github.com/hrodrig/groot/internal/analyze"
	"github.com/hrodrig/groot/internal/arcread"
)

func TestRenderExecutive_CrashLoop(t *testing.T) {
	path := packFixture(t, "crashloop")
	arc, err := arcread.Open(path)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer arc.Close()

	rep, err := analyze.Run(arc)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	md, err := analyze.RenderExecutive(rep)
	if err != nil {
		t.Fatalf("RenderExecutive: %v", err)
	}
	for _, want := range []string{
		"# groot analyze",
		"hints",
		"hypotheses",
		"run-crashloop-001",
		"abc123deadbeef0123456789abcdef",
		"CrashLoopBackOff",
		"generated by groot analyze",
	} {
		if !strings.Contains(strings.ToLower(md), strings.ToLower(want)) && !strings.Contains(md, want) {
			t.Fatalf("markdown missing %q:\n%s", want, md)
		}
	}
	lower := strings.ToLower(md)
	if strings.Contains(lower, "root cause is") || strings.Contains(lower, "diagnosed as") {
		t.Fatalf("markdown must not use definitive diagnosis verbs:\n%s", md)
	}
}

func TestRenderExecutive_Healthy(t *testing.T) {
	path := packFixture(t, "healthy")
	arc, err := arcread.Open(path)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer arc.Close()

	rep, err := analyze.Run(arc)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	md, err := analyze.RenderExecutive(rep)
	if err != nil {
		t.Fatalf("RenderExecutive: %v", err)
	}
	if !strings.Contains(md, "# groot analyze") {
		t.Fatalf("missing title:\n%s", md)
	}
	if !strings.Contains(strings.ToLower(md), "healthy") &&
		!strings.Contains(strings.ToLower(md), "empty") {
		t.Fatalf("healthy summary missing:\n%s", md)
	}
	if strings.Contains(md, "CrashLoopBackOff") {
		t.Fatalf("healthy markdown must not include CrashLoopBackOff:\n%s", md)
	}
}
